# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # All Vagrant configuration is done here. The most common configuration
    # options are documented and commented below. For a complete reference,
    # please see the online documentation at vagrantup.com.

    # Every Vagrant virtual environment requires a box to build off of.
    # config.vm.box = "precise64"
    # config.vm.box = "precise32"
    config.vm.box = "trusty64"

    # The url from where the 'config.vm.box' box will be fetched if it
    # doesn't already exist on the user's system.
    # config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    # config.vm.box_url = "http://files.vagrantup.com/precise32.box"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

    # Provision
    config.vm.provision :shell, :path => "bootstrap.sh"

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    config.vm.network :forwarded_port, guest: 80, host: 8999
    config.vm.network :forwarded_port, guest: 22, host: 2299


    # Synced folder
    # config.vm.synced_folder "../magento/", "/vagrant/httpdocs"
    # host -> guest
    config.vm.synced_folder "../magento/", "/vagrant/httpdocs", id: "vagrant-root", owner: "vagrant", group: "www-data", mount_options: ["dmode=777,fmode=777"]

    # VirtualBox setting
    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--cpus", 1]
    end

    # Host Manager
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
    config.vm.define 'magento' do |node|
        node.vm.hostname = 'magento'
        node.vm.network :private_network, ip: '192.168.99.99'
        node.hostmanager.aliases = %w(magento.dev)
    end
end
